apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-notification-hub
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-notification-hub
  template:
    metadata:
      labels:
        app: argocd-notification-hub
    spec:
      containers:
        - name: argocd-notification-hun
          image: ghcr.io/visiongeist/argocd-notification-hub:main
          imagePullPolicy: Always
          ports:
            - containerPort: 8000