apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: default
spec:
  replicas: 10
  selector:
    matchLabels:
      app: my-deployment
  template:
    metadata:
      labels:
        app: my-deployment
    spec:
      containers:
        - name: my-app-container
          image: ghcr.io/visiongeist/argocd-notification-hub@sha256:08a495ef44ed0ab17f7f6b674279f99233c9c72ab3c5885d85c1ded368f33fb9
          imagePullPolicy: Always
          ports:
            - containerPort: 8000 