# Service YAML
apiVersion: v1 
kind: Service
metadata:
  name: argocd-notification-hub
spec:
  selector:
    app: argocd-notification-hub
  ports:
    - port: 80
      targetPort: 8000
  type: LoadBalancer